#!/usr/bin/env bash
# =============================================================================
# Ralph Loop - Autonomous Coding Loop
# Generated by ralph-loop skill
#
# Usage:
#   .ralph/loop.sh [MODE] [MAX_ITERS]
#   .ralph/loop.sh plan        # Planning mode only
#   .ralph/loop.sh build       # Building mode only
#   .ralph/loop.sh both        # Plan then build
#   .ralph/loop.sh build 50    # Building mode, max 50 iterations
#
# Environment variables (override defaults):
#   RALPH_CLI     - CLI tool: claude|codex|opencode|goose (default: {{CLI}})
#   RALPH_FLAGS   - Extra flags passed to CLI
#   RALPH_MODE    - plan|build|both (default: {{MODE}})
#   RALPH_MAX     - Max iterations, 0=unlimited (default: {{MAX_ITERS}})
#   RALPH_MAX_REVIEW - Max consecutive review rounds before checkpoint (default: 15)
#
# Exit codes:
#   0   - Success (LGTM or PLANNING_COMPLETE)
#   1   - Failure (max iterations, blocked)
#   2   - Review checkpoint: agent decision needed (read .ralph/state/review-checkpoint.md)
#   130 - User Ctrl+C
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration (generated from your choices — edit as needed)
# ---------------------------------------------------------------------------
CLI="${RALPH_CLI:-{{CLI}}}"
MODE="${1:-${RALPH_MODE:-{{MODE}}}}"
MAX_ITERS="${2:-${RALPH_MAX:-{{MAX_ITERS}}}}"
BACKPRESSURE_CMD="{{BACKPRESSURE_CMD}}"

# Internal paths
RALPH_DIR=".ralph"
STATE_DIR="$RALPH_DIR/state"
LOG_FILE="$RALPH_DIR/ralph.log"
FEEDBACK_FILE="$STATE_DIR/last-feedback.txt"
ITER_FILE="$STATE_DIR/iteration.txt"

PLAN_PROMPT="$RALPH_DIR/PROMPT_plan.md"
BUILD_PROMPT="$RALPH_DIR/PROMPT_build.md"
PLAN_PHASE_SENTINEL="STATUS: PLANNING_COMPLETE"
BUILD_PHASE_SENTINEL="STATUS: COMPLETE"
BLOCKED_FILE="RALPH-BLOCKED.md"

# Review convergence — soft cap on consecutive review rounds
MAX_REVIEW_ROUNDS="${RALPH_MAX_REVIEW:-15}"
REVIEW_ROUND_FILE="$STATE_DIR/review-round.txt"
REVIEW_CHECKPOINT_FILE="$STATE_DIR/review-checkpoint.md"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log() {
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S')"
  echo -e "[$ts] $*" | tee -a "$LOG_FILE"
}

log_section() {
  echo "" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}  $*${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
  echo "" | tee -a "$LOG_FILE"
}

check_cli() {
  if ! command -v "$CLI" &>/dev/null; then
    echo -e "${RED}❌ CLI '$CLI' not found. Install it or set RALPH_CLI env var.${NC}" >&2
    echo "  claude:    https://github.com/anthropics/claude-cli"
    echo "  codex:     https://github.com/openai/codex"
    echo "  opencode:  https://github.com/opencode-ai/opencode"
    echo "  goose:     https://github.com/block/goose"
    exit 1
  fi
}

get_cli_flags() {
  # Build CLI-specific flags. Optional arg: CLI name (defaults to $CLI)
  local target="${1:-$CLI}"
  local flags="${RALPH_FLAGS:-}"
  case "$target" in
    claude)
      flags="${flags:+$flags }--dangerously-skip-permissions"
      ;;
    codex)
      flags="${flags:+$flags }--dangerously-bypass-approvals-and-sandbox"
      ;;
    opencode|goose)
      # These CLIs have auto-approval built-in
      ;;
  esac
  echo "$flags"
}

run_cli() {
  # Run a prompt through a CLI. Optional second arg: CLI name (defaults to $CLI)
  local prompt="$1"
  local target="${2:-$CLI}"
  local cli_flags
  cli_flags="$(get_cli_flags "$target")"

  case "$target" in
    claude)
      echo "$prompt" | claude $cli_flags 2>&1
      ;;
    codex)
      codex exec $cli_flags "$prompt" 2>&1
      ;;
    opencode)
      opencode run $cli_flags "$prompt" 2>&1
      ;;
    goose)
      goose run $cli_flags "$prompt" 2>&1
      ;;
    *)
      # Generic fallback
      echo "$prompt" | $target $cli_flags 2>&1
      ;;
  esac
}

inject_feedback() {
  local prompt="$1"
  if [[ -f "$FEEDBACK_FILE" && -s "$FEEDBACK_FILE" ]]; then
    local feedback
    feedback="$(cat "$FEEDBACK_FILE")"
    echo "${prompt}

---
## ⚠️ Feedback from Previous Iteration
The previous iteration did not complete successfully. Address this feedback:

${feedback}"
  else
    echo "$prompt"
  fi
}

check_blocked() {
  if [[ -f "$BLOCKED_FILE" ]]; then
    echo "" | tee -a "$LOG_FILE"
    echo -e "${RED}${BOLD}🛑 RALPH IS BLOCKED${NC}" | tee -a "$LOG_FILE"
    echo -e "${RED}Ralph created RALPH-BLOCKED.md — human intervention needed.${NC}" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    cat "$BLOCKED_FILE" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    echo -e "${YELLOW}Fix the blocker, delete RALPH-BLOCKED.md, then restart Ralph.${NC}" | tee -a "$LOG_FILE"
    return 1
  fi
  return 0
}

check_phase_complete() {
  local mode="$1"
  local sentinel
  case "$mode" in
    plan) sentinel="$PLAN_PHASE_SENTINEL" ;;
    build) sentinel="$BUILD_PHASE_SENTINEL" ;;
    *) sentinel="$BUILD_PHASE_SENTINEL" ;;
  esac
  if grep -Fq "$sentinel" "IMPLEMENTATION_PLAN.md" 2>/dev/null; then
    return 0  # complete
  fi
  return 1  # not complete
}

run_backpressure() {
  if [[ -z "$BACKPRESSURE_CMD" ]]; then
    log "⚠️  No backpressure command configured. Skipping validation."
    return 0
  fi

  log "🔧 Running backpressure: $BACKPRESSURE_CMD"
  if bash -lc "$BACKPRESSURE_CMD" 2>&1 | tee -a "$LOG_FILE"; then
    log "✅ Backpressure passed"
    # Clear feedback on success
    echo "" > "$FEEDBACK_FILE"
    return 0
  else
    local exit_code=$?
    log "❌ Backpressure FAILED (exit code $exit_code)"
    # Save failure as feedback for next iteration
    echo "Backpressure command '$BACKPRESSURE_CMD' failed with exit code $exit_code. Fix the failures before proceeding." > "$FEEDBACK_FILE"
    return $exit_code
  fi
}

git_push() {
  # Skip if no remote configured
  if ! git remote get-url origin &>/dev/null; then
    return 0
  fi
  local branch
  branch="$(git branch --show-current 2>/dev/null || echo "")"
  if [[ -n "$branch" ]]; then
    log "📤 Pushing to origin/$branch..."
    git push origin "$branch" 2>&1 | tee -a "$LOG_FILE" || {
      log "⚠️  git push failed (continuing anyway)"
    }
  fi
}

run_cross_review() {
  # Cross-review gate — pick a reviewer CLI, preferring a *different* tool
  # from the build CLI for independent review. Fallback order:
  #   build=claude → codex → claude (self)
  #   build=codex  → claude → codex (self)
  #   build=other  → claude → codex → same CLI

  local reviewer=""
  local reviewer_label=""

  # Candidates: prefer a different CLI for independence
  local candidates=()
  case "$CLI" in
    claude) candidates=(codex claude) ;;
    codex)  candidates=(claude codex) ;;
    *)      candidates=(claude codex "$CLI") ;;
  esac

  for candidate in "${candidates[@]}"; do
    if ! command -v "$candidate" &>/dev/null; then
      log "⚠️  $candidate not installed — trying next reviewer"
      continue
    fi
    # Health check: lightweight call to verify CLI is responsive (quota, auth, etc.)
    log "🩺 Health-checking $candidate..."
    if run_cli "Respond with exactly: HEALTH_OK" "$candidate" 2>/dev/null | grep -Fq "HEALTH_OK"; then
      reviewer="$candidate"
      reviewer_label="$candidate"
      break
    else
      log "⚠️  $candidate installed but not responding (quota/auth issue?) — trying next"
    fi
  done

  if [[ -z "$reviewer" ]]; then
    log "⚠️  No reviewer CLI available — skipping cross-review gate"
    return 0
  fi

  if [[ "$reviewer" == "$CLI" ]]; then
    log "ℹ️  Using $reviewer for self-review (no independent reviewer available)"
  fi

  # --- Review round tracking ---
  local review_round=0
  if [[ -f "$REVIEW_ROUND_FILE" ]]; then
    review_round="$(cat "$REVIEW_ROUND_FILE" 2>/dev/null || echo "0")"
  fi
  review_round=$((review_round + 1))
  echo "$review_round" > "$REVIEW_ROUND_FILE"
  log "📋 Review round: $review_round / $MAX_REVIEW_ROUNDS"

  log_section "🔍 ${reviewer_label} Cross-Review Gate"
  log "Running ${reviewer_label} review with fix suggestions..."

  local review_output
  local review_prompt="Review the entire codebase against specs/ directory requirements. Check:
1. Security issues
2. Architecture problems
3. Cross-module interface consistency
4. Test coverage gaps
5. Spec acceptance criteria not fully met
6. Placeholders, stubs, or incomplete implementations

If you find issues:
- List each issue clearly
- Provide a SPECIFIC fix suggestion for each (exact code changes or approach)
- End with: VERDICT: NEEDS_FIXES

If everything looks good:
- End with: VERDICT: LGTM"

  review_output="$(run_cli "$review_prompt" "$reviewer")" || true
  echo "$review_output" | tee -a "$LOG_FILE"

  if echo "$review_output" | grep -Fq "VERDICT: LGTM"; then
    log "✅ ${reviewer_label} cross-review: LGTM"
    echo "0" > "$REVIEW_ROUND_FILE"
    rm -f "$REVIEW_CHECKPOINT_FILE"
    return 0
  else
    # NEEDS_FIXES — check soft cap
    if [[ "$review_round" -ge "$MAX_REVIEW_ROUNDS" ]]; then
      log "⏸️  Review soft cap reached ($review_round/$MAX_REVIEW_ROUNDS) — writing checkpoint"
      cat > "$REVIEW_CHECKPOINT_FILE" <<CHECKPOINT
# Review Checkpoint — Agent Decision Required

**Iteration:** $(cat "$ITER_FILE")
**Review Round:** ${review_round}/${MAX_REVIEW_ROUNDS} (soft cap reached)
**Reviewer:** ${reviewer_label}
**Timestamp:** $(date '+%Y-%m-%d %H:%M:%S')

## Latest Review Feedback

${review_output}

## Decision Options

1. **Continue** — Delete this file and run \`.ralph/loop.sh build\` to continue fixing
2. **Force LGTM** — Set \`STATUS: COMPLETE\` in IMPLEMENTATION_PLAN.md, delete this file, run \`.ralph/loop.sh build\`
CHECKPOINT
      exit 2  # Special: agent decision needed
    fi

    log "❌ ${reviewer_label} found issues (round $review_round/$MAX_REVIEW_ROUNDS)"
    echo "${reviewer_label} cross-review found issues. Address ALL of the following before marking complete:

$review_output" > "$FEEDBACK_FILE"
    # Remove STATUS: COMPLETE so the loop continues
    sed -i '' 's/STATUS: COMPLETE/STATUS: IN_PROGRESS/' "IMPLEMENTATION_PLAN.md" 2>/dev/null || \
    sed -i 's/STATUS: COMPLETE/STATUS: IN_PROGRESS/' "IMPLEMENTATION_PLAN.md" 2>/dev/null
    log "🔄 STATUS: COMPLETE reverted → continuing loop with ${reviewer_label} feedback (round $review_round/$MAX_REVIEW_ROUNDS)"
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Cleanup on exit
# ---------------------------------------------------------------------------
cleanup() {
  local exit_code=$?
  if [[ $exit_code -eq 2 ]]; then
    log "⏸️  Ralph paused — review checkpoint written. Outer agent should read $REVIEW_CHECKPOINT_FILE"
  elif [[ $exit_code -ne 0 && $exit_code -ne 130 ]]; then
    log "⚠️  Ralph exited with code $exit_code"
  fi
}

trap cleanup EXIT

# Graceful Ctrl+C
handle_sigint() {
  echo "" | tee -a "$LOG_FILE"
  log "🛑 Ralph stopped by user (Ctrl+C)"
  echo -e "${YELLOW}Ralph paused. To resume, run: .ralph/loop.sh $MODE${NC}"
  exit 130
}

trap handle_sigint INT TERM

# ---------------------------------------------------------------------------
# Single loop execution
# ---------------------------------------------------------------------------
run_loop() {
  local mode="$1"  # plan or build
  local prompt_file
  local mode_label

  case "$mode" in
    plan)
      prompt_file="$PLAN_PROMPT"
      mode_label="PLANNING"
      ;;
    build)
      prompt_file="$BUILD_PROMPT"
      mode_label="BUILDING"
      ;;
    *)
      echo -e "${RED}Unknown mode: $mode. Use plan or build.${NC}" >&2
      exit 1
      ;;
  esac

  if [[ ! -f "$prompt_file" ]]; then
    echo -e "${RED}❌ Prompt file not found: $prompt_file${NC}" >&2
    echo "Did you run the ralph-loop skill to generate files?" >&2
    exit 1
  fi

  local iteration=0

  # Resume from saved iteration count if exists
  if [[ -f "$ITER_FILE" ]]; then
    iteration="$(cat "$ITER_FILE" 2>/dev/null || echo "0")"
  fi

  log_section "🐑 Ralph $mode_label Loop Starting"
  log "CLI: $CLI | Mode: $mode_label | Max: ${MAX_ITERS:-unlimited}"
  log "Log: $LOG_FILE"

  while true; do
    # --- Max iterations check ---
    if [[ "$MAX_ITERS" -gt 0 && "$iteration" -ge "$MAX_ITERS" ]]; then
      echo "" | tee -a "$LOG_FILE"
      echo -e "${RED}${BOLD}❌ Max iterations ($MAX_ITERS) reached without completion.${NC}" | tee -a "$LOG_FILE"
      log "Consider: increasing MAX_ITERS, reviewing IMPLEMENTATION_PLAN.md, or checking AGENTS.md"
      exit 1
    fi

    iteration=$((iteration + 1))
    echo "$iteration" > "$ITER_FILE"

    log_section "Iteration $iteration / ${MAX_ITERS:-∞} [$mode_label]"

    # --- BLOCKED check (before running) ---
    if ! check_blocked; then
      exit 1
    fi

    # --- Early completion check (build mode) ---
    if [[ "$mode" == "build" ]] && check_phase_complete "$mode"; then
      if run_cross_review; then
        echo -e "${GREEN}${BOLD}✅ STATUS: COMPLETE detected before iteration $iteration — cross-review approved!${NC}" | tee -a "$LOG_FILE"
        log "All tasks done. Ralph is finished."
        git_push
        exit 0
      else
        log "🔄 Early completion rejected by reviewer — running iteration $iteration with feedback"
      fi
    fi

    # --- Build prompt with feedback injection ---
    local base_prompt
    base_prompt="$(cat "$prompt_file")"
    # Replace {{ITER}} placeholder
    base_prompt="${base_prompt//\{\{ITER\}\}/$iteration}"
    # Replace {{DATE}} placeholder
    local today
    today="$(date '+%Y-%m-%d')"
    base_prompt="${base_prompt//\{\{DATE\}\}/$today}"

    local final_prompt
    final_prompt="$(inject_feedback "$base_prompt")"

    # --- Run AI CLI ---
    log "🤖 Calling $CLI..."
    if run_cli "$final_prompt" | tee -a "$LOG_FILE"; then
      log "✅ $CLI completed iteration $iteration"
    else
      local cli_exit=$?
      log "⚠️  $CLI exited with code $cli_exit (checking state anyway)"
    fi

    # --- Post-iteration checks ---

    # Check if Ralph blocked itself
    if ! check_blocked; then
      exit 1
    fi

    # Check for completion sentinel (both modes)
    if check_phase_complete "$mode"; then
      if [[ "$mode" == "build" ]]; then
        # Build mode: run cross-review before accepting completion
        if run_cross_review; then
          echo "" | tee -a "$LOG_FILE"
          echo -e "${GREEN}${BOLD}✅ STATUS: COMPLETE — cross-review passed!${NC}" | tee -a "$LOG_FILE"
          log "Ralph finished in $iteration iteration(s)."
          git_push
          exit 0
        else
          log "🔄 Reviewer rejected — continuing loop with feedback"
          # Loop continues, next iteration gets reviewer feedback via last-feedback.txt
        fi
      else
        # Plan mode: no cross-review needed
        echo "" | tee -a "$LOG_FILE"
        echo -e "${GREEN}${BOLD}✅ PLANNING_COMPLETE detected!${NC}" | tee -a "$LOG_FILE"
        log "Planning finished in $iteration iteration(s)."
        exit 0
      fi
    fi

    # --- Backpressure (build mode only) ---
    if [[ "$mode" == "build" ]]; then
      run_backpressure || {
        log "⚠️  Backpressure failed — feedback saved for next iteration"
        # Don't exit — let the loop continue with feedback injected
      }
      # Reset review round — new code was written, review starts fresh
      echo "0" > "$REVIEW_ROUND_FILE"
    fi

    # --- Git push (build mode) ---
    if [[ "$mode" == "build" ]]; then
      git_push
    fi

    log "🔄 Iteration $iteration complete. Starting next..."
    sleep 1  # Brief pause to prevent hammering
  done
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  # Validate
  check_cli

  # Setup directories
  mkdir -p "$STATE_DIR"
  touch "$LOG_FILE" "progress.txt" "AGENTS.md"
  [[ -f "IMPLEMENTATION_PLAN.md" ]] || touch "IMPLEMENTATION_PLAN.md"

  # Print banner
  echo -e "${BOLD}${CYAN}"
  echo "  ██████╗  █████╗ ██╗     ██████╗ ██╗  ██╗"
  echo "  ██╔══██╗██╔══██╗██║     ██╔══██╗██║  ██║"
  echo "  ██████╔╝███████║██║     ██████╔╝███████║"
  echo "  ██╔══██╗██╔══██║██║     ██╔═══╝ ██╔══██║"
  echo "  ██║  ██║██║  ██║███████╗██║     ██║  ██║"
  echo "  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝"
  echo -e "${NC}"
  echo -e "${CYAN}  Autonomous Coding Loop | Ralph Skill v2${NC}"
  echo -e "${CYAN}  CLI: $CLI | Mode: $MODE | Max Iterations: ${MAX_ITERS:-unlimited}${NC}"
  echo ""

  case "$MODE" in
    plan)
      run_loop plan
      ;;
    build)
      run_loop build
      ;;
    both)
      log_section "🗺️  Phase 1: PLANNING"
      run_loop plan
      log_section "🔨 Phase 2: BUILDING"
      # Reset iteration counter for build phase
      echo "0" > "$ITER_FILE"
      run_loop build
      ;;
    *)
      echo -e "${RED}❌ Unknown mode: $MODE${NC}" >&2
      echo "Usage: $0 [plan|build|both] [max_iterations]" >&2
      exit 1
      ;;
  esac
}

main "$@"
