# profile zsh:
# https://cloud.tencent.com/developer/article/1678315
# zmodload zsh/zprof
# zmodload zsh/datetime
# setopt PROMPT_SUBST
# PS4='+$EPOCHREALTIME %N:%i> '
#
# logfile=$(mktemp zsh_profile.7Pw1Ny0G)
# echo "Logging to $logfile"
# exec 3>&2 2>$logfile
#
# setopt XTRACE

# Prevent recursive startup loops (e.g. when ~/.zshrc_local accidentally sources ~/.zshrc).
typeset -gi DOTFILES_ZSHRC_LOAD_DEPTH=${DOTFILES_ZSHRC_LOAD_DEPTH:-0}
if (( DOTFILES_ZSHRC_LOAD_DEPTH > 0 )); then
  return 0
fi
(( DOTFILES_ZSHRC_LOAD_DEPTH++ ))

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="random"
ZSH_THEME="xiong-chiamiov"
# ZSH_THEME="jonathan"
# ZSH_THEME="ys"
# ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git
    autojump
    zsh-syntax-highlighting
    zsh-autosuggestions
    colored-man-pages
    sudo
    zsh-wakatime
    # zsh-vi-mode
    # we prefer emacs mode
)

source $ZSH/oh-my-zsh.sh
# Load modular zsh config files from ~/.zshrc.d.
ZSHRC_MODULE_DIR="${ZDOTDIR:-$HOME}/.zshrc.d"
for zshrc_module in "$ZSHRC_MODULE_DIR"/*.zsh(N); do
  source "$zshrc_module"
done
unset ZSHRC_MODULE_DIR zshrc_module

(( DOTFILES_ZSHRC_LOAD_DEPTH-- ))
# 在多个 shell 会话之间共享历史记录
setopt SHARE_HISTORY

# common shell setup for bash and zsh
[ -f ~/.common_shell_setup.sh ] && source ~/.common_shell_setup.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export CLASHCTL_HOME=$HOME/clashctl
[ -f $CLASHCTL_HOME/scripts/cmd/clashctl.sh ] && source $CLASHCTL_HOME/scripts/cmd/clashctl.sh

# kimi-code
export PATH="$HOME/.kimi-code/bin:$PATH"
