#!/usr/bin/env python3
"""Merge the tracked shared Codex config into the live ``$CODEX_HOME/config.toml``.

Why a merge and not a symlink
-----------------------------
Codex has no ``include``/``extends`` directive for ``config.toml`` (verified
against codex-cli 0.160.0: ``ConfigToml`` denies unknown fields and the only
extra layers are project ``.codex/config.toml``, ``--profile`` files, managed
config and the built-in defaults). Worse, Codex edits ``config.toml`` in place
at runtime and writes machine-local state into it:

* ``[projects."/abs/path"]`` trust levels
* ``[hooks.state."/abs/path:event:i:j"]`` hook trust hashes
* ``[marketplaces.*]`` sources under ``$CODEX_HOME/.tmp``
* ``[plugins.*]``, ``[notice.*]``, ``tui.model_availability_nux``

So a symlink to this repo pushes that state into git, and on macOS Codex even
replaces the symlink with a regular file. ``~/.codex/config.toml`` therefore
stays a real, machine-local file and this script re-applies the shared keys on
every install and every 15-minute sync.

Precedence (highest first), mirroring ``~/.gitconfig`` + ``~/.gitconfig_local``
------------------------------------------------------------------------------
1. ``$CODEX_HOME/config_local.toml`` — untracked per-machine overrides
2. ``<repo>/codex/config.toml`` — shared defaults, tracked in git
3. ``$CODEX_HOME/config.toml`` — live file; every key the two files above do not
   define is preserved verbatim (that is Codex's own machine state)

Run directly for a manual sync, or through
``scripts/post-install.d/30-codex-config.sh``.
"""

from __future__ import annotations

import json
import os
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SHARED = REPO / "codex" / "config.toml"
CODEX_HOME = Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
LIVE = CODEX_HOME / "config.toml"
OVERRIDE = CODEX_HOME / "config_local.toml"

BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")


def load(path: Path) -> dict:
    """Parse a TOML file; a missing file is an empty mapping."""
    if not path.exists():
        return {}
    with path.open("rb") as handle:
        return tomllib.load(handle)


def combine(*mappings: dict) -> dict:
    """Deep-merge mappings, later ones winning; tables merge, arrays replace."""
    merged: dict = {}
    for mapping in mappings:
        for key, value in mapping.items():
            if isinstance(merged.get(key), dict) and isinstance(value, dict):
                merged[key] = combine(merged[key], value)
            else:
                merged[key] = value
    return merged


def is_table(value: object) -> bool:
    return isinstance(value, dict)


def is_table_array(value: object) -> bool:
    return isinstance(value, list) and bool(value) and all(isinstance(i, dict) for i in value)


def quote(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def fmt_key(key: str) -> str:
    return key if BARE_KEY.fullmatch(key) else quote(key)


def fmt_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return quote(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, list):
        return "[{}]".format(", ".join(fmt_value(item) for item in value))
    raise TypeError(f"unsupported TOML value: {value!r}")


def emit(table: dict, prefix: str, lines: list[str]) -> None:
    """Emit one table: scalar keys first, then sub-tables, then [[arrays]].

    A table that only groups sub-tables gets no header of its own: ``[a.b]``
    already implies ``[a]``, so the shorter form stays byte-for-byte equivalent.
    """
    for key, value in table.items():
        if is_table(value) or is_table_array(value):
            continue
        lines.append(f"{fmt_key(key)} = {fmt_value(value)}")
    for key, value in table.items():
        if is_table(value):
            path = f"{prefix}{fmt_key(key)}"
            if not value or any(not is_table(v) and not is_table_array(v) for v in value.values()):
                lines.append("")
                lines.append(f"[{path}]")
            emit(value, f"{path}.", lines)
    for key, value in table.items():
        if is_table_array(value):
            path = f"{prefix}{fmt_key(key)}"
            for item in value:
                lines.append("")
                lines.append(f"[[{path}]]")
                emit(item, f"{path}.", lines)


def render(merged: dict) -> str:
    header = [
        f"# Machine-local Codex config, regenerated by {REPO}/scripts/codex-config-sync.py.",
        f"# Shared keys come from {SHARED} (tracked in git).",
        f"# Machine-only keys below are preserved as-is; per-machine overrides go in {OVERRIDE}.",
        "# Do not move this file back into the repo: Codex writes hook trust, project",
        "# trust and marketplace state here at runtime.",
        "",
    ]
    lines: list[str] = []
    emit(merged, "", lines)
    while lines and not lines[0]:
        lines.pop(0)
    return "\n".join(header + lines) + "\n"


def main() -> int:
    if not SHARED.exists():
        print(f"warn  shared config missing: {SHARED}", file=sys.stderr)
        return 1
    if not LIVE.exists() and not CODEX_HOME.is_dir():
        print(f"skip  {CODEX_HOME} does not exist (Codex not installed here)")
        return 0

    live = load(LIVE)
    shared = load(SHARED)
    override = load(OVERRIDE)
    merged = combine(live, shared, override)
    text = render(merged)

    # A symlink into the repo must be replaced even when the content is equal,
    # otherwise Codex keeps writing its machine state into git.
    symlinked = LIVE.is_symlink()
    if not symlinked and LIVE.exists() and LIVE.read_text() == text:
        print("ok    ~/.codex/config.toml already up to date")
        return 0

    tmp = CODEX_HOME / ".config.toml.tmp"
    tmp.write_text(text)
    os.chmod(tmp, 0o600)
    os.replace(tmp, LIVE)

    machine_only = [k for k in live if k not in shared and k not in override]
    detail = f", kept {len(machine_only)} machine-local table(s)" if machine_only else ""
    print(f"write ~/.codex/config.toml <- codex/config.toml{detail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
